version: 2.1

jobs:
  build:
    docker:
      - image: ubuntu:latest
    steps:
      - run: echo hi
      - run: mkdir my_workspace; touch my_workspace/foo
      - persist_to_workspace:
          root: my_workspace
          paths:
            - foo
      - run: echo "hello" > /tmp/my+artifact
      - store_artifacts:
          path: /tmp/my+artifact
    
workflows:
  version: 2
  my-workflow:
    jobs:
      - build
