version: 2.1

jobs:
  build:
    parameters:
      greeting:
        type: string
        default: hello
      phrase:
        type: string
        default: << parameters.greeting >> world
    docker:
      - image: cimg/base:2022.03
    steps:
      - run: echo << parameters.phrase >>
    
workflows:
  version: 2
  my-workflow:
    jobs:
      - build
