version: 2.1

jobs:
  build:
    docker:
      - image: ubuntu:latest
    steps:
      - run: echo hi
      - run: mkdir my_workspace; touch my_workspace/foo
      - persist_to_workspace:
          root: my_workspace
          paths:
            - foo
    
workflows:
  version: 2
  my-workflow:
    jobs:
      - build
