version: 2
jobs:
  build:
    machine:
      resource-class: windows.medium
      image: windows-server-2019-vs2019:previous
    steps:
      - run: echo hi
    
workflows:
  version: 2
  my-workflow:
    jobs:
      - build
