version: 2.1

jobs:
  build:
    machine: true
    steps:
      - checkout
      - run: echo hi > hi
      - run: echo hi2 > hi2
      - store_artifacts:
          path: hi
      - store_artifacts:
          path: hi2
      - store_test_results:
          path: test-results
      - store_test_results:
          path: test-results2
    
workflows:
  version: 2
  my-workflow:
    jobs:
      - build
