version: 2.1

jobs:
  build:
    macos: # executor type
      xcode: 11.3.0
    steps:
      - checkout
      - run: git rev-parse HEAD
      - run: echo $CIRCLE_TAG
      - run: echo $CIRCLE_SHA1 
    
workflows:
  version: 2
  my-workflow:
    jobs:
      - build:
          filters:
            tags:
              only: /.*/
