version: 2.1

jobs:
  build:
    docker:
      - image: circleci/python:3.6
    steps:
      - run: |
          echo $(getent passwd $(id -un) | cut -d: -f6)
      - checkout
    
workflows:
  version: 2
  my-workflow:
    jobs:
      - build
