version: 2.1

jobs:
  build:
    macos:
      xcode: 12.5.1
    resource_class: macos.x86.medium.gen2
    steps:
      - run: which gzip
      - run: which tar
      - run: echo $PATH
    
workflows:
  version: 2
  my-workflow:
    jobs:
      - build
