version: 2.1

jobs:
  build:
    machine: true
    resource_class: projectfrank/test
    steps:
      - run: echo hi > hi
      - run: echo hi2 > hi2
      - store_artifacts:
          path: hi
      - store_artifacts:
          path: hi2
    
workflows:
  version: 2
  my-workflow:
    jobs:
      - build
