version: 2
jobs:
  build:
    steps:
      run: echo 'build'
    
    
  test:
    steps:
      run: echo 'test'
    
  deploy:
    steps:
      run: echo 'deploy'
    
workflows:
  version: 2
  my-workflow:
    jobs:
      - build
      - test:
          requires:
            - build
      - approval:
          type: approval
          requires:
            - test
      - deploy:
          requires: 
            - test
            - approval
