version: 2.1

jobs:
  build:
    docker:
      - image: cimg/base:2020.01
    resource_class: small
    steps:
      - checkout
      - run: |
          while true; do
            echo -n '.'
            sleep 1
          done
    
workflows:
  version: 2
  my-workflow:
    jobs:
      - build
