version: 2
jobs:
  not-build:
    docker:
      - image: circleci/ruby:2.1-node-browsers
    steps:
      - run: echo 'build'
    
    
  test:
    docker:
      - image: circleci/ruby:2.1-node-browsers  
    steps:
      - run: echo 'test'
    
  deploy:
    docker:
      - image: circleci/ruby:2.1-node-browsers
    steps:
      - run: echo 'deploy'
    
workflows:
  version: 2
  my-workflow:
    jobs:
      - not-build
          filters:
            tags:
              only:
                - my-tag
      - test:
          requires:
            - not-build
      - approval:
          type: approval
          requires:
            - test
          filters:
            branches:
              only:
                - master
      - deploy:
          requires: 
            - test
            - approval
