version: 2.1

jobs:
  build:
    docker:
      - image: cimg/base:2020.01
    resource_class: small
    steps:
      - checkout
      - run: git rev-parse HEAD
      - run: echo $CIRCLE_TAG
      - run: echo $CIRCLE_SHA1
    
workflows:
  version: 2
  my-workflow:
    jobs:
      - build:
          filters:
            tags:
              only: /.*/
