version: 2
jobs:
  build:
    docker:
      - image: circleci/ruby:2.1-node-browsers
    steps:
      - run: echo 'build' > build.txt
      - run: mkdir -p workspace && mv build.txt workspace/
      - persist_to_workspace:
          root: workspace
          paths: build.txt
    
  test:
    docker:
      - image: circleci/ruby:2.1-node-browsers  
    steps:
      - run: echo 'test'
      - attach_workspace:
          at: workspace
      - run: find workspace
    
  deploy:
    docker:
      - image: circleci/ruby:2.1-node-browsers
    steps:
      - run: echo 'deploy'
    
workflows:
  version: 2
  my-workflow:
    jobs:
      - build
      - test:
          requires:
            - build
      - approval:
          type: approval
          requires:
            - test
      - deploy:
          requires: 
            - test
            - approval
