version: 2

orbs:
  win: circleci/windows@2.2.0

jobs:
  build:
    executor:
      name: win/default
      version: previous
    steps:
      - run: echo hi
    
workflows:
  version: 2
  my-workflow:
    jobs:
      - build
